openapi: '3.0.3'
info:
    title: Walk Service APIs
    version: 0.0.1
servers:
    -   url: http://localhost:8181
        description: Development server

paths:
    /management/health:
        get:
            tags:
                - HealthCheck
            summary: Health Check
            operationId: healthCheck
            responses:
                200:
                    description: Health Check

    /api/v1/users:
        get:
            tags:
                - UserV1
            summary: Get all users
            operationId: getAllUsers
            parameters:
                -   name: GetUsersCriteria
                    in: query
                    required: false
                    schema:
                        $ref: '#/components/schemas/GetUsersCriteria'
            responses:
                200:
                    description: Successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetAllUsersResponse'
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /api/v1/steps:
        post:
            tags:
                - StepV1
            summary: Record step of user by day
            operationId: recordStep
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RecordStepRequest'
            responses:
                200:
                    description: Successfully
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /api/v1/steps/weekly/{userId}:
        get:
            tags:
                - StepV1
            summary: Get weekly steps of user
            operationId: getWeeklySteps
            parameters:
                -   name: userId
                    in: path
                    required: true
                    schema:
                        type: integer
                        format: int64
            responses:
                200:
                    description: Successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetWeeklyStepsResponse'
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /api/v1/steps/monthly/{userId}:
        get:
            tags:
                - StepV1
            summary: Get monthly steps of user
            operationId: getMonthlySteps
            parameters:
                -   name: userId
                    in: path
                    required: true
                    schema:
                        type: integer
                        format: int64
            responses:
                200:
                    description: Successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetMonthlyStepsResponse'
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /api/v1/ranking:
        get:
            tags:
                - RankingV1
            summary: Get ranking by current date
            operationId: getRankingByCurrentDate
            parameters:
                -   name: GetRankingCriteria
                    in: query
                    required: false
                    schema:
                        $ref: '#/components/schemas/GetRankingCriteria'
            responses:
                200:
                    description: Create successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetRankingByDateResponse'
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    schemas:
        ErrorResponse:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string

        Page:
            type: integer
            format: int32
            default: 1
            minimum: 1

        Size:
            type: integer
            format: int32
            default: 15
            minimum: 1

        GetUsersCriteria:
            type: object
            title: GetUsersCriteria
            properties:
                page:
                    $ref: '#/components/schemas/Page'
                size:
                    $ref: '#/components/schemas/Size'

        GetAllUsersResponse:
            type: object
            title: GetAllUsersResponse
            properties:
                total:
                    type: integer
                    format: int64
                page:
                    $ref: '#/components/schemas/Page'
                size:
                    $ref: '#/components/schemas/Size'
                users:
                    type: array
                    items:
                        $ref: '#/components/schemas/UserResponseItem'

        UserResponseItem:
            type: object
            title: UserResponseItem
            properties:
                userId:
                    type: integer
                    format: int64
                name:
                    type: string
                email:
                    type: string

        GetRankingCriteria:
            type: object
            title: GetRankingCriteria
            properties:
                cursor:
                    type: string
                    description: The cursor to get next page
                size:
                    $ref: '#/components/schemas/Size'

        RecordStepRequest:
            type: object
            required:
                - userId
                - steps
            properties:
                userId:
                    type: integer
                    format: int64
                steps:
                    type: integer
                    format: int32
                    minimum: 1
                    maximum: 100000

        GetWeeklyStepsResponse:
            type: object
            properties:
                userId:
                    type: integer
                    format: int64
                totalSteps:
                    type: integer
                    format: int32
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/WeeklySteps'

        WeeklySteps:
            type: object
            properties:
                date:
                    type: string
                    pattern: ^\d{4}-\d{2}-\d{2}$
                steps:
                    type: integer
                    format: int32

        GetMonthlyStepsResponse:
            $ref: '#/components/schemas/GetWeeklyStepsResponse'

        GetRankingByDateResponse:
            type: object
            properties:
                date:
                    type: string
                    pattern: ^\d{4}-\d{2}-\d{2}$
                paging:
                    $ref: '#/components/schemas/Paging'
                ranking:
                    type: array
                    items:
                        $ref: '#/components/schemas/RankingItem'

        Paging:
            type: object
            properties:
                cursor:
                    type: string
                    description: The cursor to get next page
                hasNext:
                    type: boolean
                    description: The flag to check if there is next page
                size:
                    $ref: '#/components/schemas/Size'

        RankingItem:
            type: object
            properties:
                userId:
                    type: integer
                    format: int64
                steps:
                    type: integer
                    format: int32
